# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='quantity',
        ),
    ]
