# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='session_user_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='shopping_cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
