# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_auto_20170419_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='user_id',
            new_name='user',
        ),
    ]
