# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20170419_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='invoice_number',
        ),
    ]
