# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_remove_reservations_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
