# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_auto_20170419_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Orders',
        ),
    ]
