# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0007_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.Orders'),
        ),
    ]
