# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:36
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0010_auto_20170421_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_order_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
