# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0012_orders_shopping_cart_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='shopping_cart_details',
        ),
    ]
