# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0013_remove_orders_shopping_cart_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shopping_cart_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
